#ifndef TEST_KHEAD_H
#define TEST_KHEAD_H

#include <linux/list.h>
#include <linux/spinlock.h>
#include <linux/mutex.h>
#include <linux/mempool.h>
#include <linux/wait.h>
#include <linux/types.h>
#include <linux/kthread.h>
#include <linux/blkdev.h>
#include <linux/sysctl.h>
#include <linux/seq_file.h>
#include <linux/buffer_head.h> /* for invalidate_bdev */
#include <linux/poll.h>
#include <linux/ctype.h>
#include <linux/string.h>
#include <linux/hdreg.h>
#include <linux/proc_fs.h>
#include <linux/random.h>
#include <linux/reboot.h>
#include <linux/file.h>
#include <linux/compat.h>
#include <linux/delay.h>
#include <linux/slab.h>
#include <linux/workqueue.h>
#include <linux/mm.h>
#include <linux/timer.h>
#include <linux/thread_info.h>
#include <linux/sched.h>
#include <linux/delayacct.h>
#include <linux/percpu.h>
#include <linux/moduleparam.h>
#include <linux/dma-mapping.h>
#include <linux/irqflags.h>
#include <asm/errno.h>
//#include <asm/system.h>
#include <linux/module.h>
#include <linux/types.h>
#include <linux/moduleparam.h>
#include <linux/kernel.h>
#include <linux/pci.h>
#include <linux/interrupt.h>
#include <linux/spinlock.h>
#include <linux/delay.h>
#include <linux/dma-mapping.h>
#include <linux/mm.h>
#include <asm/page.h>
#include <linux/async_tx.h>
#include <linux/dmaengine.h>
#include <linux/raid/xor.h>
#include <linux/proc_fs.h>
#include <asm/tlbflush.h> 
#include <linux/vmalloc.h>
#include <linux/mm.h>
#include <linux/sched.h>
#include <linux/io.h>
#include <asm/cacheflush.h>
#include <asm/pgtable.h>

#endif
